language: php
php:
  - 5.5
  - 5.6

services:
  - redis-server

before_script:
  - composer self-update
  - composer update 1>/dev/null
  - phpenv config-add php_conf_test.ini

script:
  - phpunit --bootstrap Commen.inc.php test/unit/
